---
abstract: 'database migration utility for git managed SQL extended L<GitDDL>'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GitDDL-Migrator
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  GitDDL::Migrator:
    file: lib/GitDDL/Migrator.pm
    version: 0.02
requires:
  GitDDL: 0
  Mouse: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/GitDDL-Migrator/issues
  homepage: https://github.com/Songmu/GitDDL-Migrator
  repository: git://github.com/Songmu/GitDDL-Migrator.git
version: 0.02
